/* Generated by scripts/build_gallery.py — do not edit by hand. */
window.GALLERY = {
  "series": [
    {
      "slug": "bible-belt",
      "numeral": "I",
      "title": "Bible Belt",
      "kind": "nocturne",
      "layout": "scroll",
      "excerpt": [
        "The Bible Belt gets its name for a reason — a church on nearly every corner, in a region where the culture built around them is visibly aging out. This project sits in the gap between traditionalism and modernism: the way a generation raised inside a specific era of Southern Baptist or Catholic practice finds comfort and identity in these buildings, and the way a Millennial or Gen Z viewer, raised in the same towns, often doesn't.",
        "That gap shows up in strange, specific ways. Small prairie towns with more than forty churches and barely twenty people aren't, as you'd assume, evidence of a community united by shared faith — they're the opposite. Even within the same race, ethnicity, and religious background, people have splintered into smaller factions, unable to agree closely enough on theology to worship under one roof.",
        "Bible Belt holds that tension without resolving it — sincere belief alongside the decline of the institutions that housed it, and the uncomfortable overlap between religion, politics, and money that runs through both. Religion makes some people feel comforted, some at peace, and others completely alienated from the idea of faith itself. Everyone brings their own interpretation, and the work is meant to let the viewer arrive at their own read on both the signs and the religion behind them. This is an ongoing project, built in part through interviews with pastors, church members, and non-religious individuals to understand their perspective firsthand."
      ],
      "plates": [
        {
          "title": "Untitled 01",
          "image_url": "media/bible-belt/01.jpg",
          "shape": "tall",
          "session": null
        },
        {
          "title": "Untitled 02",
          "image_url": "media/bible-belt/02.jpg",
          "shape": "wide",
          "session": null
        },
        {
          "title": "Untitled 03",
          "image_url": "media/bible-belt/03.jpg",
          "shape": "tall",
          "session": null
        },
        {
          "title": "Untitled 04",
          "image_url": "media/bible-belt/04.jpg",
          "shape": "tall",
          "session": null
        },
        {
          "title": "Untitled 05",
          "image_url": "media/bible-belt/05.jpg",
          "shape": "tall",
          "session": null
        },
        {
          "title": "Untitled 06",
          "image_url": "media/bible-belt/06.jpg",
          "shape": "",
          "session": null
        },
        {
          "title": "Untitled 07",
          "image_url": "media/bible-belt/07.jpg",
          "shape": "wide",
          "session": null
        },
        {
          "title": "Untitled 08",
          "image_url": "media/bible-belt/08.jpg",
          "shape": "wide",
          "session": null
        },
        {
          "title": "Untitled 09",
          "image_url": "media/bible-belt/09.jpg",
          "shape": "tall",
          "session": null
        },
        {
          "title": "Untitled 10",
          "image_url": "media/bible-belt/10.jpg",
          "shape": "tall",
          "session": null
        },
        {
          "title": "Untitled 11",
          "image_url": "media/bible-belt/11.jpg",
          "shape": "wide",
          "session": null
        },
        {
          "title": "Untitled 12",
          "image_url": "media/bible-belt/12.jpg",
          "shape": "wide",
          "session": null
        },
        {
          "title": "Untitled 13",
          "image_url": "media/bible-belt/13.jpg",
          "shape": "tall",
          "session": null
        },
        {
          "title": "Untitled 14",
          "image_url": "media/bible-belt/14.jpg",
          "shape": "tall",
          "session": null
        },
        {
          "title": "Untitled 15",
          "image_url": "media/bible-belt/15.jpg",
          "shape": "tall",
          "session": null
        },
        {
          "title": "Untitled 16",
          "image_url": "media/bible-belt/16.jpg",
          "shape": "wide",
          "session": null
        },
        {
          "title": "Untitled 17",
          "image_url": "media/bible-belt/17.jpg",
          "shape": "wide",
          "session": null
        },
        {
          "title": "Untitled 18",
          "image_url": "media/bible-belt/18.jpg",
          "shape": "tall",
          "session": null
        },
        {
          "title": "Untitled 19",
          "image_url": "media/bible-belt/19.jpg",
          "shape": "tall",
          "session": null
        },
        {
          "title": "Untitled 20",
          "image_url": "media/bible-belt/20.jpg",
          "shape": "tall",
          "session": null
        },
        {
          "title": "Untitled 21",
          "image_url": "media/bible-belt/21.jpg",
          "shape": "",
          "session": null
        },
        {
          "title": "Untitled 22",
          "image_url": "media/bible-belt/22.jpg",
          "shape": "wide",
          "session": null
        },
        {
          "title": "Untitled 23",
          "image_url": "media/bible-belt/23.jpg",
          "shape": "wide",
          "session": null
        },
        {
          "title": "Untitled 24",
          "image_url": "media/bible-belt/24.jpg",
          "shape": "tall",
          "session": null
        },
        {
          "title": "Untitled 25",
          "image_url": "media/bible-belt/25.jpg",
          "shape": "tall",
          "session": null
        },
        {
          "title": "Untitled 26",
          "image_url": "media/bible-belt/26.jpg",
          "shape": "wide",
          "session": null
        },
        {
          "title": "Untitled 27",
          "image_url": "media/bible-belt/27.jpg",
          "shape": "",
          "session": null
        },
        {
          "title": "Untitled 28",
          "image_url": "media/bible-belt/28.jpg",
          "shape": "tall",
          "session": null
        },
        {
          "title": "Untitled 29",
          "image_url": "media/bible-belt/29.jpg",
          "shape": "",
          "session": null
        },
        {
          "title": "Untitled 30",
          "image_url": "media/bible-belt/30.jpg",
          "shape": "wide",
          "session": null
        },
        {
          "title": "Untitled 31",
          "image_url": "media/bible-belt/31.jpg",
          "shape": "wide",
          "session": null
        },
        {
          "title": "Untitled 32",
          "image_url": "media/bible-belt/32.jpg",
          "shape": "tall",
          "session": null
        },
        {
          "title": "Untitled 33",
          "image_url": "media/bible-belt/33.jpg",
          "shape": "tall",
          "session": null
        },
        {
          "title": "Untitled 34",
          "image_url": "media/bible-belt/34.jpg",
          "shape": "tall",
          "session": null
        },
        {
          "title": "Untitled 35",
          "image_url": "media/bible-belt/35.jpg",
          "shape": "tall",
          "session": null
        },
        {
          "title": "Untitled 36",
          "image_url": "media/bible-belt/36.jpg",
          "shape": "",
          "session": null
        },
        {
          "title": "Untitled 37",
          "image_url": "media/bible-belt/37.jpg",
          "shape": "",
          "session": null
        },
        {
          "title": "Untitled 38",
          "image_url": "media/bible-belt/38.jpg",
          "shape": "tall",
          "session": null
        },
        {
          "title": "Untitled 39",
          "image_url": "media/bible-belt/39.jpg",
          "shape": "tall",
          "session": null
        },
        {
          "title": "Untitled 40",
          "image_url": "media/bible-belt/40.jpg",
          "shape": "wide",
          "session": null
        },
        {
          "title": "Untitled 41",
          "image_url": "media/bible-belt/41.jpg",
          "shape": "tall",
          "session": null
        },
        {
          "title": "Untitled 42",
          "image_url": "media/bible-belt/42.jpg",
          "shape": "wide",
          "session": null
        },
        {
          "title": "Untitled 43",
          "image_url": "media/bible-belt/43.jpg",
          "shape": "wide",
          "session": null
        },
        {
          "title": "Untitled 44",
          "image_url": "media/bible-belt/44.jpg",
          "shape": "tall",
          "session": null
        },
        {
          "title": "Untitled 45",
          "image_url": "media/bible-belt/45.jpg",
          "shape": "tall",
          "session": null
        }
      ]
    },
    {
      "slug": "abandoned-america",
      "numeral": "II",
      "title": "Abandoned America",
      "kind": "votive",
      "layout": "scroll",
      "excerpt": [
        "Abandoned America documents what's left after the people have gone — farmhouses, water towers, and small-town landmarks weathering and falling in on themselves across the high plains of Texas, Oklahoma, and Kansas, and the forested hills of the Ozarks in Arkansas and Missouri. These were homes. These were the places everyone in town used to pass through. The project sits with one unanswerable question: how does a place get like this — and what does it mean that the people who left assumed, wrongly, it would stay the same without them."
      ],
      "plates": [
        {
          "title": "Untitled 01",
          "image_url": "media/abandoned-america/01.jpg",
          "shape": "tall",
          "session": null
        },
        {
          "title": "Untitled 02",
          "image_url": "media/abandoned-america/02.jpg",
          "shape": "wide",
          "session": null
        },
        {
          "title": "Untitled 03",
          "image_url": "media/abandoned-america/03.jpg",
          "shape": "wide",
          "session": null
        },
        {
          "title": "Untitled 04",
          "image_url": "media/abandoned-america/04.jpg",
          "shape": "tall",
          "session": null
        },
        {
          "title": "Untitled 05",
          "image_url": "media/abandoned-america/05.jpg",
          "shape": "tall",
          "session": null
        },
        {
          "title": "Untitled 06",
          "image_url": "media/abandoned-america/06.jpg",
          "shape": "tall",
          "session": null
        },
        {
          "title": "Untitled 07",
          "image_url": "media/abandoned-america/07.jpg",
          "shape": "",
          "session": null
        },
        {
          "title": "Untitled 08",
          "image_url": "media/abandoned-america/08.jpg",
          "shape": "tall",
          "session": null
        },
        {
          "title": "Untitled 09",
          "image_url": "media/abandoned-america/09.jpg",
          "shape": "tall",
          "session": null
        },
        {
          "title": "Untitled 10",
          "image_url": "media/abandoned-america/10.jpg",
          "shape": "tall",
          "session": null
        },
        {
          "title": "Untitled 11",
          "image_url": "media/abandoned-america/11.jpg",
          "shape": "tall",
          "session": null
        },
        {
          "title": "Untitled 12",
          "image_url": "media/abandoned-america/12.jpg",
          "shape": "tall",
          "session": null
        },
        {
          "title": "Untitled 13",
          "image_url": "media/abandoned-america/13.jpg",
          "shape": "tall",
          "session": null
        },
        {
          "title": "Untitled 14",
          "image_url": "media/abandoned-america/14.jpg",
          "shape": "tall",
          "session": null
        },
        {
          "title": "Untitled 15",
          "image_url": "media/abandoned-america/15.jpg",
          "shape": "tall",
          "session": null
        },
        {
          "title": "Untitled 16",
          "image_url": "media/abandoned-america/16.jpg",
          "shape": "tall",
          "session": null
        },
        {
          "title": "Untitled 17",
          "image_url": "media/abandoned-america/17.jpg",
          "shape": "tall",
          "session": null
        },
        {
          "title": "Untitled 18",
          "image_url": "media/abandoned-america/18.jpg",
          "shape": "tall",
          "session": null
        },
        {
          "title": "Untitled 19",
          "image_url": "media/abandoned-america/19.jpg",
          "shape": "tall",
          "session": null
        },
        {
          "title": "Untitled 20",
          "image_url": "media/abandoned-america/20.jpg",
          "shape": "wide",
          "session": null
        },
        {
          "title": "Untitled 21",
          "image_url": "media/abandoned-america/21.jpg",
          "shape": "tall",
          "session": null
        },
        {
          "title": "Untitled 22",
          "image_url": "media/abandoned-america/22.jpg",
          "shape": "tall",
          "session": null
        },
        {
          "title": "Untitled 23",
          "image_url": "media/abandoned-america/23.jpg",
          "shape": "tall",
          "session": null
        },
        {
          "title": "Untitled 24",
          "image_url": "media/abandoned-america/24.jpg",
          "shape": "wide",
          "session": null
        },
        {
          "title": "Untitled 25",
          "image_url": "media/abandoned-america/25.jpg",
          "shape": "tall",
          "session": null
        },
        {
          "title": "Untitled 26",
          "image_url": "media/abandoned-america/26.jpg",
          "shape": "tall",
          "session": null
        },
        {
          "title": "Untitled 27",
          "image_url": "media/abandoned-america/27.jpg",
          "shape": "wide",
          "session": null
        },
        {
          "title": "Untitled 28",
          "image_url": "media/abandoned-america/28.jpg",
          "shape": "tall",
          "session": null
        },
        {
          "title": "Untitled 29",
          "image_url": "media/abandoned-america/29.jpg",
          "shape": "tall",
          "session": null
        },
        {
          "title": "Untitled 30",
          "image_url": "media/abandoned-america/30.jpg",
          "shape": "wide",
          "session": null
        },
        {
          "title": "Untitled 31",
          "image_url": "media/abandoned-america/31.jpg",
          "shape": "tall",
          "session": null
        },
        {
          "title": "Untitled 32",
          "image_url": "media/abandoned-america/32.jpg",
          "shape": "wide",
          "session": null
        },
        {
          "title": "Untitled 33",
          "image_url": "media/abandoned-america/33.jpg",
          "shape": "tall",
          "session": null
        },
        {
          "title": "Untitled 34",
          "image_url": "media/abandoned-america/34.jpg",
          "shape": "tall",
          "session": null
        },
        {
          "title": "Untitled 35",
          "image_url": "media/abandoned-america/35.jpg",
          "shape": "tall",
          "session": null
        },
        {
          "title": "Untitled 36",
          "image_url": "media/abandoned-america/36.jpg",
          "shape": "wide",
          "session": null
        },
        {
          "title": "Untitled 37",
          "image_url": "media/abandoned-america/37.jpg",
          "shape": "wide",
          "session": null
        },
        {
          "title": "Untitled 38",
          "image_url": "media/abandoned-america/38.jpg",
          "shape": "",
          "session": null
        },
        {
          "title": "Untitled 39",
          "image_url": "media/abandoned-america/39.jpg",
          "shape": "tall",
          "session": null
        },
        {
          "title": "Untitled 40",
          "image_url": "media/abandoned-america/40.jpg",
          "shape": "tall",
          "session": null
        }
      ]
    },
    {
      "slug": "portraits",
      "numeral": "III",
      "title": "Portraits",
      "kind": "still",
      "layout": "sessions",
      "excerpt": [
        "Each session is a collaboration with a specific person, named and dated, rather than a moment caught in passing."
      ],
      "plates": [
        {
          "title": "Paul S. — February",
          "image_url": "media/portraits/01.jpg",
          "shape": "tall",
          "session": "Paul S. — February"
        },
        {
          "title": "Paul S. — February",
          "image_url": "media/portraits/02.jpg",
          "shape": "tall",
          "session": "Paul S. — February"
        },
        {
          "title": "Paul S. — February",
          "image_url": "media/portraits/03.jpg",
          "shape": "tall",
          "session": "Paul S. — February"
        },
        {
          "title": "Brooke N. — March",
          "image_url": "media/portraits/04.jpg",
          "shape": "tall",
          "session": "Brooke N. — March"
        },
        {
          "title": "Brooke N. — March",
          "image_url": "media/portraits/05.jpg",
          "shape": "",
          "session": "Brooke N. — March"
        },
        {
          "title": "Brooke N. — March",
          "image_url": "media/portraits/06.jpg",
          "shape": "tall",
          "session": "Brooke N. — March"
        },
        {
          "title": "Brooke N. — March",
          "image_url": "media/portraits/07.jpg",
          "shape": "tall",
          "session": "Brooke N. — March"
        },
        {
          "title": "Brooke N. — March",
          "image_url": "media/portraits/08.jpg",
          "shape": "tall",
          "session": "Brooke N. — March"
        },
        {
          "title": "Brooke N. — March",
          "image_url": "media/portraits/09.jpg",
          "shape": "tall",
          "session": "Brooke N. — March"
        },
        {
          "title": "Brooke N. — March",
          "image_url": "media/portraits/10.jpg",
          "shape": "tall",
          "session": "Brooke N. — March"
        },
        {
          "title": "Brooke N. — March",
          "image_url": "media/portraits/11.jpg",
          "shape": "tall",
          "session": "Brooke N. — March"
        },
        {
          "title": "Brooke N. — March",
          "image_url": "media/portraits/12.jpg",
          "shape": "wide",
          "session": "Brooke N. — March"
        },
        {
          "title": "Brooke N. — March",
          "image_url": "media/portraits/13.jpg",
          "shape": "tall",
          "session": "Brooke N. — March"
        },
        {
          "title": "Brooke N. — March",
          "image_url": "media/portraits/14.jpg",
          "shape": "tall",
          "session": "Brooke N. — March"
        },
        {
          "title": "Brooke N. — March",
          "image_url": "media/portraits/15.jpg",
          "shape": "tall",
          "session": "Brooke N. — March"
        },
        {
          "title": "Hannah L. — March",
          "image_url": "media/portraits/16.jpg",
          "shape": "tall",
          "session": "Hannah L. — March"
        },
        {
          "title": "Hannah L. — April",
          "image_url": "media/portraits/17.jpg",
          "shape": "tall",
          "session": "Hannah L. — April"
        },
        {
          "title": "Hannah L. — April",
          "image_url": "media/portraits/18.jpg",
          "shape": "tall",
          "session": "Hannah L. — April"
        },
        {
          "title": "Hannah L. — April",
          "image_url": "media/portraits/19.jpg",
          "shape": "tall",
          "session": "Hannah L. — April"
        },
        {
          "title": "Hannah L. — April",
          "image_url": "media/portraits/20.jpg",
          "shape": "tall",
          "session": "Hannah L. — April"
        },
        {
          "title": "Hannah L. — April",
          "image_url": "media/portraits/21.jpg",
          "shape": "tall",
          "session": "Hannah L. — April"
        },
        {
          "title": "Hannah L. — April",
          "image_url": "media/portraits/22.jpg",
          "shape": "tall",
          "session": "Hannah L. — April"
        },
        {
          "title": "Hannah L. — April",
          "image_url": "media/portraits/23.jpg",
          "shape": "tall",
          "session": "Hannah L. — April"
        },
        {
          "title": "Hannah L. — April",
          "image_url": "media/portraits/24.jpg",
          "shape": "tall",
          "session": "Hannah L. — April"
        },
        {
          "title": "Pranav N. — April",
          "image_url": "media/portraits/25.jpg",
          "shape": "tall",
          "session": "Pranav N. — April"
        },
        {
          "title": "Pranav N. — April",
          "image_url": "media/portraits/26.jpg",
          "shape": "tall",
          "session": "Pranav N. — April"
        },
        {
          "title": "Pranav N. — April",
          "image_url": "media/portraits/27.jpg",
          "shape": "",
          "session": "Pranav N. — April"
        },
        {
          "title": "Pranav N. — April",
          "image_url": "media/portraits/28.jpg",
          "shape": "",
          "session": "Pranav N. — April"
        },
        {
          "title": "Pranav N. — April",
          "image_url": "media/portraits/29.jpg",
          "shape": "tall",
          "session": "Pranav N. — April"
        },
        {
          "title": "Diego and Isaac — May",
          "image_url": "media/portraits/30.jpg",
          "shape": "wide",
          "session": "Diego and Isaac — May"
        },
        {
          "title": "Manny U. — May",
          "image_url": "media/portraits/31.jpg",
          "shape": "",
          "session": "Manny U. — May"
        },
        {
          "title": "Manny U. — May",
          "image_url": "media/portraits/32.jpg",
          "shape": "",
          "session": "Manny U. — May"
        },
        {
          "title": "Manny U. — May",
          "image_url": "media/portraits/33.jpg",
          "shape": "tall",
          "session": "Manny U. — May"
        },
        {
          "title": "Manny U. — May",
          "image_url": "media/portraits/34.jpg",
          "shape": "tall",
          "session": "Manny U. — May"
        },
        {
          "title": "Dani And Flavie — June",
          "image_url": "media/portraits/35.jpg",
          "shape": "tall",
          "session": "Dani And Flavie — June"
        },
        {
          "title": "Elena R. — June",
          "image_url": "media/portraits/36.jpg",
          "shape": "tall",
          "session": "Elena R. — June"
        },
        {
          "title": "Elena R. — June",
          "image_url": "media/portraits/37.jpg",
          "shape": "tall",
          "session": "Elena R. — June"
        },
        {
          "title": "Elena R. — June",
          "image_url": "media/portraits/38.jpg",
          "shape": "tall",
          "session": "Elena R. — June"
        },
        {
          "title": "Hannah L. — June",
          "image_url": "media/portraits/39.jpg",
          "shape": "tall",
          "session": "Hannah L. — June"
        },
        {
          "title": "Hannah L. — June",
          "image_url": "media/portraits/40.jpg",
          "shape": "tall",
          "session": "Hannah L. — June"
        }
      ]
    },
    {
      "slug": "wanderings",
      "numeral": "IV",
      "title": "Wanderings",
      "kind": "mixed",
      "layout": "grid",
      "excerpt": [],
      "plates": [
        {
          "title": "A Moth To a Flame",
          "image_url": "media/wanderings/01.jpg",
          "shape": "tall",
          "session": null
        },
        {
          "title": "American Muscle",
          "image_url": "media/wanderings/02.jpg",
          "shape": "tall",
          "session": null
        },
        {
          "title": "Americas Most Haunted Hotel",
          "image_url": "media/wanderings/03.jpg",
          "shape": "tall",
          "session": null
        },
        {
          "title": "Antique Church Sound System",
          "image_url": "media/wanderings/04.jpg",
          "shape": "wide",
          "session": null
        },
        {
          "title": "As Above So Below",
          "image_url": "media/wanderings/05.jpg",
          "shape": "wide",
          "session": null
        },
        {
          "title": "Bible Belt Bamboo Forest",
          "image_url": "media/wanderings/06.jpg",
          "shape": "tall",
          "session": null
        },
        {
          "title": "Bring Me Towards The Light",
          "image_url": "media/wanderings/07.jpg",
          "shape": "tall",
          "session": null
        },
        {
          "title": "California Dream",
          "image_url": "media/wanderings/08.jpg",
          "shape": "wide",
          "session": null
        },
        {
          "title": "Chasing A Forest Fire",
          "image_url": "media/wanderings/09.jpg",
          "shape": "wide",
          "session": null
        },
        {
          "title": "Dancing With Two Left Feet",
          "image_url": "media/wanderings/10.jpg",
          "shape": "wide",
          "session": null
        },
        {
          "title": "Don’t Wake Me From This Dream",
          "image_url": "media/wanderings/11.jpg",
          "shape": "tall",
          "session": null
        },
        {
          "title": "Empty Places",
          "image_url": "media/wanderings/12.jpg",
          "shape": "tall",
          "session": null
        },
        {
          "title": "Escaping The Matrix",
          "image_url": "media/wanderings/13.jpg",
          "shape": "",
          "session": null
        },
        {
          "title": "Finding My Way Home",
          "image_url": "media/wanderings/14.jpg",
          "shape": "tall",
          "session": null
        },
        {
          "title": "Five Dollars To Know Your Fate",
          "image_url": "media/wanderings/15.jpg",
          "shape": "wide",
          "session": null
        },
        {
          "title": "Following The Path To Salvation",
          "image_url": "media/wanderings/16.jpg",
          "shape": "wide",
          "session": null
        },
        {
          "title": "Free To Travel Anywhere",
          "image_url": "media/wanderings/17.jpg",
          "shape": "wide",
          "session": null
        },
        {
          "title": "Freedom At Last",
          "image_url": "media/wanderings/18.jpg",
          "shape": "tall",
          "session": null
        },
        {
          "title": "Groom Texas",
          "image_url": "media/wanderings/19.jpg",
          "shape": "",
          "session": null
        },
        {
          "title": "H-Town",
          "image_url": "media/wanderings/20.jpg",
          "shape": "tall",
          "session": null
        },
        {
          "title": "Her Name Is ‘Alice’",
          "image_url": "media/wanderings/21.jpg",
          "shape": "tall",
          "session": null
        },
        {
          "title": "Hot Summer Day",
          "image_url": "media/wanderings/22.jpg",
          "shape": "wide",
          "session": null
        },
        {
          "title": "House on The Praire",
          "image_url": "media/wanderings/23.jpg",
          "shape": "tall",
          "session": null
        },
        {
          "title": "I Heard The Woods Call My Name",
          "image_url": "media/wanderings/24.jpg",
          "shape": "wide",
          "session": null
        },
        {
          "title": "I Saw Something In The Window",
          "image_url": "media/wanderings/25.jpg",
          "shape": "wide",
          "session": null
        },
        {
          "title": "Im Always Feeling Watched Here",
          "image_url": "media/wanderings/26.jpg",
          "shape": "tall",
          "session": null
        },
        {
          "title": "Into New Worlds",
          "image_url": "media/wanderings/27.jpg",
          "shape": "wide",
          "session": null
        },
        {
          "title": "Lost In A Labyrinth",
          "image_url": "media/wanderings/28.jpg",
          "shape": "tall",
          "session": null
        },
        {
          "title": "Lost In The Fog",
          "image_url": "media/wanderings/29.jpg",
          "shape": "tall",
          "session": null
        },
        {
          "title": "Meet Me At The Altar",
          "image_url": "media/wanderings/30.jpg",
          "shape": "tall",
          "session": null
        },
        {
          "title": "Party Rocker",
          "image_url": "media/wanderings/31.jpg",
          "shape": "wide",
          "session": null
        },
        {
          "title": "Reds and Blues Tonight",
          "image_url": "media/wanderings/32.jpg",
          "shape": "tall",
          "session": null
        },
        {
          "title": "Sodium Lights and Crushed Shadows",
          "image_url": "media/wanderings/33.jpg",
          "shape": "wide",
          "session": null
        },
        {
          "title": "Solar Panels",
          "image_url": "media/wanderings/34.jpg",
          "shape": "tall",
          "session": null
        },
        {
          "title": "Supercar In Texas",
          "image_url": "media/wanderings/35.jpg",
          "shape": "wide",
          "session": null
        },
        {
          "title": "The Eyes That Glow",
          "image_url": "media/wanderings/36.jpg",
          "shape": "tall",
          "session": null
        },
        {
          "title": "The Hills Have Eyes",
          "image_url": "media/wanderings/37.jpg",
          "shape": "",
          "session": null
        },
        {
          "title": "The Three Wise Men",
          "image_url": "media/wanderings/38.jpg",
          "shape": "tall",
          "session": null
        },
        {
          "title": "This Is My Silent Hill",
          "image_url": "media/wanderings/39.jpg",
          "shape": "tall",
          "session": null
        },
        {
          "title": "Used and Abused",
          "image_url": "media/wanderings/40.jpg",
          "shape": "tall",
          "session": null
        }
      ]
    }
  ],
  "carousel": [
    "media/carousel/01.jpg",
    "media/carousel/02.jpg",
    "media/carousel/03.jpg",
    "media/carousel/04.jpg",
    "media/carousel/05.jpg",
    "media/carousel/06.jpg",
    "media/carousel/07.jpg",
    "media/carousel/08.jpg",
    "media/carousel/09.jpg",
    "media/carousel/10.jpg",
    "media/carousel/11.jpg",
    "media/carousel/12.jpg",
    "media/carousel/13.jpg",
    "media/carousel/14.jpg",
    "media/carousel/15.jpg",
    "media/carousel/16.jpg",
    "media/carousel/17.jpg",
    "media/carousel/18.jpg",
    "media/carousel/19.jpg",
    "media/carousel/20.jpg",
    "media/carousel/21.jpg"
  ],
  "inPassing": {
    "excerpt": [
      "In passing collects short, atmospheric videos and each clip is observed, not staged: a few seconds of someone else's ordinary life, held long enough to feel like it belonged to you too."
    ],
    "clips": [
      {
        "title": "Emergency Church",
        "src": "media/in-passing/01.mp4",
        "poster": "media/in-passing/01.jpg"
      },
      {
        "title": "Houston Old Head",
        "src": "media/in-passing/02.mp4",
        "poster": "media/in-passing/02.jpg"
      },
      {
        "title": "Lens Flares",
        "src": "media/in-passing/03.mp4",
        "poster": "media/in-passing/03.jpg"
      },
      {
        "title": "Melancholy Night",
        "src": "media/in-passing/04.mp4",
        "poster": "media/in-passing/04.jpg"
      },
      {
        "title": "Out Getting Ribs",
        "src": "media/in-passing/05.mp4",
        "poster": "media/in-passing/05.jpg"
      },
      {
        "title": "Places I shouldn’t Be",
        "src": "media/in-passing/06.mp4",
        "poster": "media/in-passing/06.jpg"
      },
      {
        "title": "Rollin’ Thunder",
        "src": "media/in-passing/07.mp4",
        "poster": "media/in-passing/07.jpg"
      },
      {
        "title": "The Lowest Point Of Life",
        "src": "media/in-passing/08.mp4",
        "poster": "media/in-passing/08.jpg"
      },
      {
        "title": "Watching The Night Pass",
        "src": "media/in-passing/09.mp4",
        "poster": "media/in-passing/09.jpg"
      }
    ]
  },
  "ephemera": {
    "headline": "Signage, artifacts, and printed matter collected alongside the main body of work — the smaller, stranger evidence of how faith shows up in daily life here.",
    "plates": []
  }
};
